from __future__ import annotations

import json
from pathlib import Path

CATALOG = Path(__file__).resolve().parents[1] / "src" / "i18n" / "locales" / "ja.json"

PATCH = {
    "studio": {
        "split": {
            "emptyHint": "SillyTavernカード（JSONまたはPNG）を開いてください。どのプレイヤーでもインポートできるキャラクター部分と、KPだけが取り込むワールド機構へ分解します。",
            "open": "カードを開く…",
            "openAnother": "別のカードを開く…",
            "parseFailed": "カードを読み取れませんでした: {{detail}}",
            "worldCard": "ワールド機構を含むカード",
            "plainCard": "通常のペルソナカード",
            "counts": "フックスクリプト{{hooks}}件 · 変数宣言{{vars}}件 · EJSブロック{{ejs}}件 · 秘密エントリ{{secret}}件",
            "characterHalf": "キャラクター部分",
            "characterHint": "EJSを除去し、変数宣言とフックを切り離した、プレイヤーが安全に自己インポートできる部分です。自由に編集でき、書き出しにはここに表示された内容が使われます。",
            "worldHalf": "ワールド部分",
            "worldHint": "KPのワールドインポートだけが持ち込む内容です。下でMVUツリーを型付き変数へ昇格させた後、モジュール全体をパックのソースとして書き出せます。",
            "fields": {
                "description": "説明",
                "personality": "性格",
                "scenario": "シナリオ",
                "firstMes": "最初のメッセージ",
                "mesExample": "会話例",
                "creatorNotes": "作者メモ",
            },
            "loreKept": "通常ロア{{n}}件はキャラクター部分に残ります。",
            "exportClean": "クリーンなSTカードを保存",
            "exportNative": "ネイティブカードを保存",
            "toForge": "Forgeで編集",
            "toPack": "ワールド部分を.lwpackソースとして書き出す…",
            "hooksTitle": "フック（{{n}}件）",
            "noHooks": "このカードにはフックスクリプトがありません。",
            "ejsTitle": "EJSテンプレート（{{n}}件）",
            "ejsHint": "実行可能なテンプレート部分はキャラクター側から除去されています。元カードでは有効なまま保持され、パックはKPのワールドインポート用に元カードをそのまま含めます。",
            "promoteTitle": "変数への昇格（末端{{n}}件）",
            "exposeTitle": "公開候補",
            "exposeHint": "MVUの末端項目は、KPが公開するまでプレイヤーパネルへ表示されません。次の行がパックのインストールメモへ入ります:",
            "promote": {
                "include": "昇格",
                "hint": "各InitVarの末端項目を型付き変数の下書きにします。すべての行を確認または編集してください。チェックを外した行は、MVUツリーにそのまま残ります。",
                "empty": "昇格できるInitVarの末端項目はありません。",
                "aiFill": "AI: IDとラベルを補完",
                "truncated": "末端項目の上限（200件）に達しました。残りはMVUツリーに残ります。",
            },
            "note": {
                "floatRounded": "小数を丸めました（Engineの数値は整数です）",
                "idGenerated": "仮IDです。分かりやすい名前を付けてください",
                "listKept": "リスト値のためMVUツリーに残します",
                "containerKept": "入れ子の値のためMVUツリーに残します",
                "nullKept": "null値のためMVUツリーに残します",
                "enumGuessed": "説明から選択肢型を推定しました",
                "boundsGuessed": "説明から範囲を推定しました",
            },
            "reattach": "ファイルを再添付",
            "reattachHint": "編集内容は復元されましたが、カードの元データは復元されませんでした。パック作成へ渡す前に、{{name}}（{{size}} bytes、sha256 {{hash}}…）を再添付してください。",
            "reattached": "{{name}}を再添付しました。",
            "reattachNeeded": "カードの元データがありません。先にファイルを再添付してください。",
        },
        "ai": {
            "open": "AI下書き…",
            "settings": "AIとEngineの設定",
            "settingsTitle": "AIとEngineの設定",
            "desktopOnly": "AI下書きと認証情報の保存はデスクトップアプリでのみ利用できます。",
            "kind": "プロバイダー",
            "kinds": {
                "openai": "OpenAI互換",
                "anthropic": "Anthropic",
            },
            "baseUrl": "Base URL",
            "model": "モデル",
            "maxTokens": "最大出力トークン数",
            "apiKey": "APIキー",
            "maxTokensUnset": "プロバイダーの最大値",
            "maxTokensHint": "空欄にするとリクエストに上限を付けず、プロバイダー側の最大値が適用されます。ほとんどの場合はこちらが適切です。1回の呼び出しで使用できる量を制限したい場合だけ指定してください。これは1応答の出力上限であり、モデルのコンテキストウィンドウとは別の値です。モデルの出力上限を超える値は拒否されます。",
            "keyPlaceholder": "sk-…",
            "showKey": "表示",
            "hideKey": "隠す",
            "forgetKey": "消去",
            "keyHint": "他の設定と同様に、この端末へ平文で保存されます。リクエストはネイティブ側から送信されるため、キーがWebページへ渡ることはありません。ただし、この端末のユーザープロファイルへアクセスできる人は読み取れます。ここへ保存してよい専用キーを使用してください。",
            "engineRepo": "Engine checkout（任意）",
            "engineRepoHint": "Loreweaver Engineのcheckoutへのパスです。PATH上にloreweaver-serverバイナリがない場合も、`python -m app`によるパックビルドを利用できます。",
            "browse": "参照…",
            "done": "完了",
            "panelTitle": "AIカード下書き",
            "needsSetup": "先にプロバイダー、モデル、APIキーを設定してください。",
            "openSettings": "設定を開く",
            "mode": "下書きの種類",
            "modes": {
                "world": "ワールドカード（モジュール）",
                "character": "キャラクターカード（ペルソナ）",
            },
            "describe": "作成したいカードを説明",
            "refine": "変更内容を伝える（会話を継続）",
            "worldPlaceholder": "疑念がターンごとに高まる、水没したCoCの港町。秘密の儀式段階があり、KPは誰が霧を見たかを管理する…",
            "characterPlaceholder": "短い言葉で話し、知っていることをすべては語らない、疲れた灯台守…",
            "generate": "下書きを生成",
            "regenerate": "送信",
            "working": "処理中…",
            "startOver": "最初からやり直す",
            "rejected": "{{n}}回試行しましたが、下書きは決定論的検証を通過しませんでした。何も保存されていません。",
            "summary": "型付き変数{{vars}}件 · ワールドブック{{lore}}件 · フックスクリプト{{hooks}}件",
            "apply": "自分のプロジェクトへ追加",
            "providerPreset": "プロバイダープリセット",
            "providerPresets": {
                "deepseek": "DeepSeek",
                "openai": "OpenAI",
                "anthropic": "Anthropic",
                "custom": "カスタム",
            },
            "deepseekProTempWarning": "deepseek-v4-proはtemperatureを指定するとthinking modeの品質が低下します。最適な推論性能を得るには、プリセットからtemperatureを外すか、別のモデルへ切り替えてください。",
            "promptPreset": "プロンプトプリセット",
            "builtinPrompts": "内蔵プロンプト",
            "managePresets": "管理…",
            "presetInUse": "プリセット「{{name}}」: プロンプト断片{{segments}}件と入力済みスロット{{slots}}件がsystem promptの先頭に入り、内蔵JSON契約は引き続き適用されます。",
            "presets": {
                "open": "プロンプトプリセット",
                "title": "プロンプトプリセット（SillyTavernからインポート）",
                "import": "STプリセットをインポート…",
                "parseFailed": "プリセットを解析できませんでした: {{detail}}",
                "saved": "プリセットを保存しました。",
                "exported": "書き出しました。",
                "exportCopied": "クリップボードへコピーしました（ここでは保存ダイアログは表示されません）。",
                "empty": "プリセットはまだありません。SillyTavernのcompletion preset（JSON）をインポートしてください。プロンプト、2層の有効化設定、サンプリングパラメーター、ST拡張を省略せず保持します。",
                "stats": "プロンプト{{total}}件 · 実効{{enabled}}件 · {{kb}} KB",
                "activeBadge": "使用中",
                "setActive": "Forgeで使用",
                "deactivate": "プリセットを無効化（内蔵プロンプトを使用）",
                "export": "JSONを書き出す",
                "deleteConfirm": "プリセット「{{name}}」を削除しますか？この操作は元に戻せません。",
                "back": "← 戻る",
                "name": "プリセット名",
                "discard": "破棄",
                "save": "ローカルプリセットとして保存",
                "sampling": "サンプリングパラメーター",
                "samplingUnsentHint": "薄く表示された値は保持されますが送信されません。ST専用の設定や乱数seedが該当し、最大トークン数はStudio側の設定が優先されます。",
                "macros": "マクロレポート",
                "noMacros": "このプリセットにはSTマクロがありません。",
                "macroHint": "{{kinds}}種類のマクロ名が合計{{total}}回使われています。この実行環境で展開できるのは{{supported}}件で、それ以外はそのままモデルへ渡されます。",
                "extensions": "ST拡張（非実行）",
                "extensionsHint": "regex scriptやtavern helperなどのST専用機構はプリセットと一緒に保持されますが、Studioでは実行されません。",
                "warnings": "インポート時の注意（{{n}}件）",
                "moreWarnings": "ほか{{n}}件",
                "groupSlots": "注入スロット",
                "groupEnabled": "有効",
                "groupDisabled": "無効",
                "notInOrder": "順序リスト外",
                "slotChip": "スロット",
                "chars": "{{n}}文字",
                "malformedKept": "解析できないエントリ{{n}}件は、アセット内にそのまま保持されています（上には表示されません）。",
                "packHint": "プレイ用のKPスタイルプリセットとして配布する場合は、JSONを書き出してパックへ含めてください。Engineは単一プロンプト構造に従い、6つの節へどう対応させるか、また対応させないかを判断します。Studioは注入位置を保証しません。",
                "slots": {
                    "personaDescription": "ペルソナ説明（スロット）",
                    "charDescription": "キャラクター説明（スロット）",
                    "charPersonality": "キャラクター性格（スロット）",
                    "scenario": "シナリオ（スロット）",
                    "worldInfoBefore": "ワールド情報 · 前（スロット）",
                    "worldInfoAfter": "ワールド情報 · 後（スロット）",
                    "dialogueExamples": "会話例（スロット）",
                    "chatHistory": "チャット履歴（スロット）",
                },
            },
        },
    }
}


def merge(target: dict, patch: dict) -> None:
    for key, value in patch.items():
        if isinstance(value, dict) and isinstance(target.get(key), dict):
            merge(target[key], value)
        else:
            target[key] = value


data = json.loads(CATALOG.read_text(encoding="utf-8"))
merge(data, PATCH)
CATALOG.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
